baseURL = "/"
title = ""
subtitle = ""
theme = "beautifulhugo"
contentDir = "content"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
    homeTitle = "Welcome" # Set a different text for the header on the home page
    subtitle = "My name is Kevin DeVrou, I'm a full stack developer. "
    mainSections = ["blog","blogs"]
    hideAuthor = false
#    since = 2022
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true
    readingTime = true
    wordCount = true
    useHLJS = true
    socialShare = true
    delayDisqus = true
    showRelatedPosts = true

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
#  name = "Some Person"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
#  facebook = "username"
#  github = "username"
#  gitlab = "username"
#  bitbucket = "username"
#  twitter = "username"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"
#  codepen = "username"
#  mastodon = "url"
#  kaggle = "username"
#  weibo = "username"
#  slack = "username"
#  discord = "invite code (https://discord.gg/XXXXXXX)"
#  strava = "userid"

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 1
[[menu.main]]
    name = "Skills"
    url = "page/skills"
    weight = 2
[[menu.main]]
    name = "Work"
    url = "page/portfolio"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "page/contact"
    weight = 4
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 5
